#!/bin/bash -x

rm -rf build
npm run build

cp -R node_modules build/
cp package.json build/

cat > build/serve <<\EOF
#!/bin/bash
. "$CREDENTIALS_DIRECTORY/secrets"
export PIMBL_2CAPTCHA_API_KEY

cd "$(dirname "$0")"
exec node index.js
EOF
chmod +x build/serve

rsync -rlp --chmod=Dg+s,ug+rw,o-w,+X --del build/ pimbl.mou.fo:/opt/pimbl/app/

ssh pimbl.mou.fo sudo systemctl restart pimbl.service
